---
name: "🧚‍♂️ Feature Request"
description: "Wouldn’t it be nice if 💭"
labels: feature
body:
  - type: checkboxes
    id: search
    attributes:
      label: Please avoid duplicates
      options:
        - label: I checked [all open feature requests](https://github.com/gr2m/github-project/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: What’s missing?
      description: Describe your feature idea
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Describe the problem you are facing
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you tried
      description: Describe the workarounds you tried so far and how they worked for you
    validations:
      required: true
  - type: checkboxes
    id: contributor
    attributes:
      label: Would you be interested in contributing the feature?
      options:
        - label: "yes"
